change_scene:
  name: Change Scene
  description: Change the scene/snapshot on the mixer
  target:
    entity:
      # integration: ha_behringer_mixer
  fields:
    scene_number:
      required: true
      selector:
        text:
        #number:
        #  min: 0
        #  max: 100
    #entity_id:
    #  required: true
    #  selector:
    #    entity:
    #      domain: ha_behringer_mixer
